<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/QuickConvert.Core/QuickConvert.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../../src/QuickConvert.App/DarkTitleBar.cs"
             Link="Ui/DarkTitleBar.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../src/QuickConvert.App/App.xaml"
          Link="Ui/App.xaml"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../src/QuickConvert.App/MainWindow.xaml"
          Link="Ui/MainWindow.xaml"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
