<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>QuickConvert</AssemblyName>
    <ApplicationIcon>../../assets/branding/quickconvert.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../QuickConvert.Core/QuickConvert.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="../../assets/branding/quickconvert.ico"
              Link="Assets/quickconvert.ico" />
  </ItemGroup>
</Project>
